const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const T={uz:{book:"Stol band qilish",h1:"SAFIR — TA’M SAN’ATI",hp:"Har bir taom — hikoya. Shef qo’lidan chiqqan nafis ta’mlar va unutilmas kechalar.",vm:"Menyuni ko’rish",n_about:"Biz haqimizda",ah:"Ta’m — bu san’at",ap:"2014-yildan beri SAFIR Toshkent qalbida mehmonlarni eng sara mahsulotlar va zamonaviy pazandalik bilan mamnun etib keladi.",ac:"Bizning oshxonamiz mahalliy fermerlar mahsulotlari va jahon texnikalarini uyg’unlashtiradi.",n_menu:"Menyu",mh:"Bizning menyu",ot:"Maxsus taklif",oh:"Bugungi maxsus taklif",op:"Premium steyk, kartoshka pyuresi va sharob sousi — faqat bugun 30% chegirma bilan.",ct:"Bosh shef",cp:"Aziz Karimov Parij va Istanbul restoranlarida ishlagan, milliy ta’mlarni zamonaviy talqinda taqdim etadi.",ce:"15 yillik tajriba · 3 ta xalqaro mukofot",n_gallery:"Galereya",gh:"Lahzalar",n_services:"Xizmatlar",sh:"Bizning xizmatlar",n_reviews:"Sharhlar",rh:"Mehmonlar fikri",bh:"Stolni band qiling",fn:"Ism",fp:"Telefon",fd:"Sana",ft:"Vaqt",fgu:"Mehmonlar soni",fc:"Izoh",n_contact:"Aloqa",kh:"Biz bilan bog’laning",ka:"Manzil",kad:"Toshkent, Amir Temur ko’chasi 15",kw:"Ish vaqti",kwh:"Har kuni 10:00 – 24:00",fd2:"Zamonaviy oshxona va yuksak xizmat markazi.",nav:"Sahifalar",nl:"Yangiliklar",sub:"Obuna",h:"Bosh sahifa",kun:"KUN",soat:"SOAT",min:"DAQ",sek:"SEK",add:"Qo’shish",added:"Buyurtmaga qo’shildi",ok:"Rahmat! Stolingiz band qilindi ✓",err:"Iltimos, maydonlarni to’ldiring",subok:"Obuna bo’ldingiz!",g:"mehmon",cats:["Barchasi","Nonushta","Salatlar","Sho’rvalar","Asosiy taomlar","Grill","Desertlar","Ichimliklar"],nv:["Bosh sahifa","Biz haqimizda","Menyu","Galereya","Xizmatlar","Sharhlar","Aloqa"],st:["yil tajriba","ta taom","mehmon","reyting"],gl:["Interer","Steyk","Shef","Mehmonlar","Atmosfera","Desert"],sv:[["Bronlash","Onlayn stol band qilish"],["Yetkazib berish","Uyingizgacha tez yetkazamiz"],["Catering","Tadbirlar uchun taomlar"],["Private events","Yopiq VIP zallar"],["Tug’ilgan kun","Bayramni bizda nishonlang"],["Business lunch","Ish uchun tez va to?yimli tushlik"]]},
ru:{book:"Забронировать столик",h1:"SAFIR — ИСКУССТВО ВКУСА",hp:"Каждое блюдо — история. Изысканные вкусы от шефа и незабываемые вечера.",vm:"Посмотреть меню",n_about:"О нас",ah:"Вкус — это искусство",ap:"С 2014 года SAFIR в самом сердце Ташкента радует гостей отборными продуктами и современной кухней.",ac:"Наша кухня объединяет продукты местных фермеров и мировые техники.",n_menu:"Меню",mh:"Наше меню",ot:"Спецпредложение",oh:"Специальное предложение дня",op:"Премиальный стейк, картофельное пюре и винный соус — только сегодня со скидкой 30%.",ct:"Шеф-повар",cp:"Азиз Каримов работал в ресторанах Парижа и Стамбула и подаёт национальные вкусы в современном прочтении.",ce:"15 лет опыта · 3 международные награды",n_gallery:"Галерея",gh:"Моменты",n_services:"Услуги",sh:"Наши услуги",n_reviews:"Отзывы",rh:"Мнение гостей",bh:"Забронируйте столик",fn:"Имя",fp:"Телефон",fd:"Дата",ft:"Время",fgu:"Количество гостей",fc:"Комментарий",n_contact:"Контакты",kh:"Свяжитесь с нами",ka:"Адрес",kad:"Ташкент, улица Амира Темура, 15",kw:"Часы работы",kwh:"Ежедневно 10:00 – 24:00",fd2:"Современная кухня и высокий уровень сервиса.",nav:"Страницы",nl:"Новости",sub:"Подписаться",h:"Главная",kun:"ДН",soat:"ЧАС",min:"МИН",sek:"СЕК",add:"Добавить",added:"Добавлено в заказ",ok:"Спасибо! Столик забронирован ✓",err:"Пожалуйста, заполните поля",subok:"Вы подписались!",g:"гост.",cats:["Все","Завтраки","Салаты","Супы","Основные блюда","Grill","Десерты","Напитки"],nv:["Главная","О нас","Меню","Галерея","Услуги","Отзывы","Контакты"],st:["лет опыта","блюд","гостей","рейтинг"],gl:["Интерьер","Стейк","Шеф","Гости","Атмосфера","Десерт"],sv:[["Бронирование","Онлайн-бронь столика"],["Доставка","Быстро привезём домой"],["Catering","Еда для ваших мероприятий"],["Private events","Закрытые VIP-залы"],["Дни рождения","Отпразднуйте у нас"],["Бизнес-ланч","Быстрый и сытный обед"]]}};
const IDS=["home","about","menu","gallery","services","reviews","contact"];
// [cat,emoji,uz,ru,descUz,descRu,price,badge]
const D=[[1,"img/omlet.jpg","Omlet Safir","Омлет Safir","Qo’ziqorin va pishloqli","С грибами и сыром",42000,"new"],[1,"img/pancake.jpg","Pancake","Панкейки","Ega siropi bilan","С кленовым сиропом",48000],[1,"img/avokado.jpg","Avokado tost","Тост с авокадо","Qaynatilgan tuxum bilan","С яйцом пашот",56000,"pop"],
[2,"img/sezar.jpg","Sezar salati","Салат Цезарь","Tovuq, parmezan, kruton","Курица, пармезан, гренки",68000,"pop"],[2,"img/yunon.jpg","Yunon salati","Греческий салат","Feta va zaytun","Фета и оливки",54000],[2,"img/caprese.jpg","Burrata salati","Салат с буррата","Pomidor va pesto","Томаты и песто",76000,"new"],
[3,"img/kremshurva.jpg","Krem-sho’rva","Крем-суп","Qo’ziqorinli","Грибной",46000,"pop"],[3,"img/lagmon.jpg","Lag’mon","Лагман","Qo’lda cho’zilgan","Домашняя лапша",52000],[3,"img/tomyam.jpg","Tomyam","Том-ям","Dengiz mahsulotlari bilan","С морепродуктами",78000,"new"],
[4,"img/losos.jpg","Losos","Лагман","Limon sousi bilan","В лимонном соусе",145000,"pop"],[4,"img/pasta.jpg","Pasta Karbonara","Паста Карбонара","Guanchale va pekorino","Гуанчале и пекорино",72000],[4,"img/pitsa.jpg","Pitstsa Margarita","Паста Карбонара","Mozzarella, rayhon","Моцарелла, базилик",64000],
[5,"img/ribay.jpg","Ribay steyk","Стейк Рибай","300 g, marmar mol go’shti","300 г, мраморная говядина",245000,"pop"],[5,"img/tovuq.jpg","Tovuq steyk","Куриный стейк","Grilda, sabzavotlar bilan","На гриле с овощами",89000],[5,"img/burger.jpg","Safir burger","Бургер Safir","Mol go’shti, cheddar","Говядина, чеддер",78000,"new"],
[6,"img/cheesecake.jpg","Cheesecake","Грибной","Nyu-York uslubida","Нью-Йорк",42000,"pop"],[6,"img/tiramisu.jpg","Tiramisu","Панкейки","Klassik italyan","Классический итальянский",46000],[6,"img/fondan.jpg","Fondan","Лагман","Iliq shokolad markazi","С тёплой шоколадной начинкой",48000,"new"],
[7,"img/latte.jpg","Kofe Latte","Кофе Латте","Arabika","Грибной",28000],[7,"img/limonad.jpg","Limonad","Грибной","Yalpiz va limon","Мята и лимон",32000,"pop"],[7,"img/sharbat.jpg","Yangi sharbat","Свежий сок","Apelsin, 300 ml","Апельсин, 300 мл",38000]];
const RV=[["Malika R.","5","Ajoyib muhit va mazali steyk! Xizmat yuqori darajada.","Потрясающая атмосфера и вкуснейший стейк! Сервис на высоте.","12.09.2026"],["Andrey K.","5","Biznes uchrashuv uchun ideal joy. Losos juda yoqdi.","Идеальное место для деловой встречи. Лосось — восторг.","03.09.2026"],["Dilnoza S.","4","Tug’ilgan kunni shu yerda nishonladik, hammasi zo’r edi.","Отмечали день рождения — всё было отлично.","28.08.2026"],["Sergey P.","5","Desertlar shunchaki mo’jiza, albatta qaytamiz.","Десерты — просто чудо, обязательно вернёмся.","15.08.2026"]];
const SI=["📅","🛵","🎉","🥂","🎂","💼"],GI=["img/interior.jpg","img/steak.jpg","img/chef.jpg","img/mehmonlar.jpg","img/atmosfera.jpg","img/desert.jpg"];
let L="uz",cat=0,fav=new Set(),ri=0;
try{L=localStorage.getItem("l")||(navigator.language.startsWith("ru")?"ru":"uz")}catch(e){}
const t=k=>T[L][k];
function toast(m){const d=document.createElement("div");d.className="to";d.textContent=m;$("#ts").append(d);setTimeout(()=>d.remove(),3500)}
function menu(){$("#tb").innerHTML=t("cats").map((c,i)=>`<button role="tab" class="${i==cat?"on":""}" data-c="${i}">${c}</button>`).join("");
$("#mg").innerHTML=D.map((d,i)=>[d,i]).filter(([d])=>!cat||d[0]==cat).map(([d,i],k)=>{const n=L=="uz"?0:1;return`<article class="mc" style="animation-delay:${k*60}px"><div class="mi"><img src="${d[1]}" alt="${d[2]}" loading="lazy"></div>${d[7]?`<span class="bd">${d[7]=="pop"?(L=="uz"?"Mashhur":"Хит"):(L=="uz"?"Yangi":"Новинка")}</span>`:""}<button class="hr ${fav.has(i)?"on":""}" data-f="${i}" aria-label="favorite">♥</button><div class="mb"><h3>${d[2+n]}</h3><p>${d[4+n]}</p><div class="mf"><b>${d[6].toLocaleString("ru-RU")} so’m</b><button class="add" data-a="${i}">+ ${t("add")}</button></div></div></article>`}).join("")}
function lang(){const s=$$("[data-t]");document.documentElement.lang=L;s.forEach(e=>{e.textContent=t(e.dataset.t)});
$("#nv").innerHTML=IDS.map((id,i)=>`<a href="#${id}" data-n="${id}">${t("nv")[i]}</a>`).join("");
$("#st").innerHTML=[["10+",10],["50+",50],["20K+",20],["4.9",4.9]].map((s,i)=>`<div><b data-x="${s[1]}" data-s="${s[0].replace(/[\d.]+/,"")}">${s[0]}</b><small>${t("st")[i]}</small></div>`).join("");
$("#fl1").innerHTML=IDS.map((id,i)=>`<a href="#${id}">${t("nv")[i]}</a>`).join("");$("#fl2").innerHTML=t("cats").slice(1,6).map(c=>`<a href="#menu">${c}</a>`).join("");
$("#gg").innerHTML=GI.map((e,i)=>`<button data-g="${i}" aria-label="${t("gl")[i]}"><img src="${e}" alt="${t("gl")[i]}" loading="lazy"><small>${t("gl")[i]}</small></button>`).join("");
$("#sv").innerHTML=t("sv").map((s,i)=>`<div><i>${SI[i]}</i><h3>${s[0]}</h3><p>${s[1]}</p></div>`).join("");
$("#rt").innerHTML=RV.map((r,i)=>`<div class="rc"><span class="av">${r[0][0]}</span><b>${r[0]}</b> <span>${"★".repeat(r[1])}${"☆".repeat(5-r[1])}</span><p>“${r[L=="uz"?2:3]}”</p><small>${r[4]}</small></div>`).join("");
$("#dt").innerHTML=RV.map((_,i)=>`<button data-r="${i}" class="${i==ri?"on":""}" aria-label="${i+1}"></button>`).join("");
const g=$("#fg"),v=g.value||"2";g.innerHTML=[1,2,3,4,5,6,8,10].map(n=>`<option ${n==v?"selected":""} value="${n}">${n} ${t("g")}</option>`).join("");
menu();cd();slide(ri);document.body.classList.remove("sw");void document.body.offsetWidth;document.body.classList.add("sw");obs()}
function cd(){const n=new Date(),e=new Date(n);e.setHours(24,0,0,0);let s=Math.floor((e-n)/1e3);const p=x=>String(x).padStart(2,"0");
$("#cd").innerHTML=[["soat",s/3600|0],["min",s%3600/60|0],["sek",s%60]].map(a=>`<div><b>${p(a[1])}</b><small>${t(a[0])}</small></div>`).join("")}
setInterval(cd,1e3);
function slide(i){ri=(i+RV.length)%RV.length;const w=$(".rc");if(!w)return;const step=w.offsetWidth+(innerWidth>=900?20:0);$("#rt").style.transform=`translateX(${-ri*step}px)`;$$("#dt button").forEach((b,k)=>b.classList.toggle("on",k==ri))}
setInterval(()=>slide(ri+1),5500);addEventListener("resize",()=>slide(ri));
let io;function obs(){io&&io.disconnect();io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");e.target.querySelectorAll("[data-x]").forEach(c=>{if(c.done)return;c.done=1;const to=+c.dataset.x,sf=c.dataset.s,dec=to%1?1:0,t0=performance.now();(function f(n){const p=Math.min((n-t0)/1600,1);c.textContent=(to*p).toFixed(dec)+(p<1?"":sf);if(p<1)requestAnimationFrame(f)})(t0)});io.unobserve(e.target)}}),{threshold:.15});$$(".rv").forEach(e=>{e.classList.remove("in");io.observe(e)})}
document.addEventListener("click",e=>{const b=e.target.closest("button,a");if(!b)return;const d=b.dataset;
if(d.c!==undefined){cat=+d.c;menu()}
if(d.f!==undefined){const i=+d.f;fav.has(i)?fav.delete(i):fav.add(i);b.classList.toggle("on")}
if(d.a!==undefined)toast(`${D[d.a][2+(L=="uz"?0:1)]} — ${t("added")}`);
if(d.g!==undefined){$("#lb div").innerHTML=`<img src="${GI[d.g]}" alt="">`;$("#lb").classList.add("o")}
if(d.r!==undefined)slide(+d.r);
if(b.closest("nav")&&b.tagName=="A"){$("#nv").classList.remove("o");$("#bg").classList.remove("o")}});
$("#lb").onclick=()=>$("#lb").classList.remove("o");addEventListener("keydown",e=>e.key=="Escape"&&$("#lb").classList.remove("o"));
$("#bg").onclick=()=>{$("#nv").classList.toggle("o");$("#bg").classList.toggle("o")};
$("#lg").onclick=()=>{L=L=="uz"?"ru":"uz";try{localStorage.setItem("l",L)}catch(e){}lang()};
$("#th").onclick=()=>{const r=document.documentElement,dk=r.dataset.theme?r.dataset.theme=="dark":matchMedia("(prefers-color-scheme:dark)").matches;r.dataset.theme=dk?"light":"dark";try{localStorage.setItem("th",r.dataset.theme)}catch(e){}};
try{const s=localStorage.getItem("th");if(s)document.documentElement.dataset.theme=s}catch(e){}
$("#fd").min=new Date().toISOString().slice(0,10);
$("#fm").onsubmit=e=>{e.preventDefault();if(!["#fn","#fp","#fd","#ft"].every(s=>$(s).value.trim()))return toast(t("err"));toast(t("ok"));e.target.reset();$("#ft").value="19:00"};
$("#nb").onclick=()=>{if($("#ne").value.includes("@")){toast(t("subok"));$("#ne").value=""}else toast(t("err"))};
const tp=$("#top");tp.onclick=()=>scrollTo({top:0});
addEventListener("scroll",()=>{tp.classList.toggle("v",scrollY>700);let c="home";IDS.forEach(id=>{const el=document.getElementById(id);if(el&&el.getBoundingClientRect().top<200)c=id});$$("nav a").forEach(a=>a.classList.toggle("on",a.dataset.n==c))},{passive:true});
for(let i=0;i<30;i++){const p=document.createElement("i");p.className="pt";p.style.cssText=`left:${Math.random()*100}%;bottom:-10px;animation-duration:${8+Math.random()*10}s;animation-delay:${Math.random()*8}s`;$("#home").append(p)}
lang();addEventListener("load",()=>setTimeout(()=>$("#ld").classList.add("x"),700));setTimeout(()=>$("#ld").classList.add("x"),2500);
